### ISSUE TITLE
does nothing

### ISSUE THREAD

**Issue by ZxverOwner** [amakvana/Bat-2-Exec#3]
title explains it

**Comment by amakvana** [comment]
Drag your batch script over the Bat2Exe.bat file and the exe will be generated and placed in the same directory as the batch file resides.

Tried it just now and works as expected

**Comment by MohandL3G** [comment]
Yeah just drag the bat file and it'll create the exe file

Working fine on my end

**Comment by YV99king** [comment]
@ZxverOwner me too

**Comment by amakvana** [comment]
This issue has been closed because there has been no response to our request from the original author. With only the information that is currently in the issue, we don't have enough information to take action.

Please reach out if you have or find the answers we need so that we can investigate further.

Thanks!
